version: "3.7"
services:
  peeringdb-cache:
    image: docker.io/route64/peeringdb-cache
    container_name: peeringdb-cache
    volumes:
      - ./peeringdb-cache:/data
    ports:
      - '8777:8080'
    environment:
      - PEERINGDB_API_KEY=your-peeringdb-api-key
