version: "3.7"
services:
  peeringdb-cache:
    image: peeringdb-cache:latest
    container_name: peeringdb-cache
    volumes:
      - ./peeringdb-cache:/data
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PEERINGDB_API_KEY=your-peeringdb-api-key
